<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="wwwroot\css\Login\" />
    <Folder Include="wwwroot\Scripts\Acceso\" />
    <Folder Include="wwwroot\Scripts\Configuracion\" />
    <Folder Include="wwwroot\Scripts\EtapaAutorizacion\" />
    <Folder Include="wwwroot\Scripts\ModeloAutorizacion\" />
    <Folder Include="wwwroot\Scripts\ChequeTest\" />
    <Folder Include="wwwroot\Scripts\Usuario\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.2" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="10.0.2" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="10.0.3" />
    <PackageReference Include="Scrutor" Version="7.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DAO\DAO.csproj" />
    <ProjectReference Include="..\DTO\DTO.csproj" />
    <ProjectReference Include="..\Helpers\Helpers.csproj" />
    <ProjectReference Include="..\INTERFACES\INTERFACES.csproj" />
    <ProjectReference Include="..\SERVICES\SERVICES.csproj" />
  </ItemGroup>

</Project>
